server.port=8080
spring.application.name=lifexp-demo-backend
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/lifexp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

openai.api.key=${OPENAI_API_KEY:}
